# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Selection features
#' @description function to perform selection giving Mirror statistic and FDR level
#' @param M mirror statistic of all features
#' @param q the nominal FDR level
#' @return the selected features that are considered significant 
#' @export
Selection <- function(M, q) {
    .Call('_SA24204176_Selection', M, q)
}

